// React imports...
import React from "react";

// Nexts.js imports...
import type { Metadata } from "next";

// Font families from Google Fonts imports...
import { Inter } from "next/font/google";

// StyleSheet imports...
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}